name: dogma_codegen_convert
version: 0.0.1
description: Code generation for the dogma_convert libraries.
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
environment:
  sdk: '>=1.14.0-any <2.0.0'
dependencies:
  dogma_codegen:
    path: ../dogma-codegen
  dogma_codegen_model:
    path: ../dogma-codegen-model
  dogma_source_analyzer:
    path: ../dogma-source-analyzer
  logging: ^0.11.3
dev_dependencies:
  test: ^0.12.13
  build_test: ^0.1.0
  dogma_codegen_test:
    path: ../dogma-codegen-test
